remote_theme: bvnierop/hyde

permalink:        pretty
relative_url:     true

title:            Bart van Nierop
tagline:          'lifelong learner, problem solver and tinkerer'
description: >-
  Hi, I'm Bart. I'm a lifelong learner, problem solver and tinkerer.
  Oh... and I also develop software occasionally.

url:              'https://bvnierop.nl'
baseurl:          ''

author:
  name:           'Bart van Nierop'
  picture:        '/img/photo.jpeg'

paginate:         5

collections:
  - external_links

analytics:
  goat_counter: bvnierop

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
